#ifndef DISCRETE_INPUT_CONF_H_
#define DISCRETE_INPUT_CONF_H_

#define BUTTON_RESET_ID    				    0
#define BUTTON_TAMPER_ID				    1
#define BUTTON_220_SENSOR_ID		        2

// #define DISCRETE_INPUT_ENABLE_DEBUG_MESSAGES 1

#endif /* DISCRETE_INPUT_CONF_H_ */
